# Generated by Django 2.1.5 on 2019-01-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='presence',
            field=models.CharField(max_length=50),
        ),
    ]
