# Generated by Django 2.1.5 on 2019-01-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190123_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='app.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='presence',
            field=models.BooleanField(default=False),
        ),
    ]
