# Generated by Django 2.1.5 on 2019-01-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190124_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('delivery_relevance', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('address', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('work_time', models.CharField(max_length=100)),
                ('time_delivery', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='vcard',
            new_name='videocard',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_product',
            field=models.ManyToManyField(related_name='orders', to='app.Product'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='shops',
            field=models.ManyToManyField(related_name='deliveries', to='app.Shop'),
        ),
    ]
