# Generated by Django 2.1.5 on 2019-01-28 15:36

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190127_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='slug',
            field=models.CharField(default=app.models.generateUUID, editable=False, max_length=36, unique=True),
        ),
    ]
